apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-cluster-autoscaler.fullname" . }}
  labels:
    {{- include "eks-cluster-autoscaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    {{- include "eks-cluster-autoscaler.selectorLabels" . | nindent 4 }}
