apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eks-cluster-autoscaler.labels" . | nindent 4 }}
  annotations: {{ toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: true